version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 12345
      DB_NAME: master
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: master
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
